[project]
name = "examples"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pardeqsi",
]

[tool.uv.sources]
pardeqsi = { path = "../../pardeqsi" }

[dependency-groups]
dev = [
    "scipy-stubs>=1.16.2.4",
]
